version: '3'

services:
  web:
    build: .
    ports:
      - 5000:5000
    depends_on:
      - mongo
  mongo:
    image: mongo:3.7.9
    ports:
      - 27021:27017
    volumes:
      - ./db:/data/db
